name: Python CI with Basic Clean Code

on: [push]

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install quality tools
      run: |
        pip install flake8 black pytest

    - name: Format code with Black
      run: |
        black .

    - name: Run linter
      run: |
        flake8 . --count --max-complexity=10 --max-line-length=88 --statistics

    - name: Run tests
      run: |
        pytest test.py
