on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      run: |
       git clone https://github.com/zeynab-gh/setion2.git
     
    - name: Install Python and pip
      run: sudo apt-get update && sudo apt-get install -y python3 python3-pip
  
    - name: Install depencies
       run: pip install -r requirements.txt

    - name: Run tests
       run: pytest test.py

    
