name: Python CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

  

    - name: Run tests
      run: |
        # روش ۱: اجرای همه تست‌ها
        pytest -v
        
        # روش ۲: اجرای فایل خاص
        # python -m pytest test_game.py -v
        
        # روش ۳: اجرای با pattern
        # pytest test*.py -v
